server {
    listen 80 default_server;         # nasłuchiwanie na porcie 80 dla IPv4
    listen [::]:80 default_server;    # nasłuchiwanie na porcie 80 dla IPv6
    server_name _;                    # domyślny serwer, odpowiada na wszystkie nazwy domen
    server_tokens off;                # wyłączenie informacji o wersji Nginx w nagłówkach odpowiedzi, zwiększa bezpieczeństwo          

    root /app/;                       # katalog publiczny serwera, u mnie cały projekt
    index index.php;                  # domyślny plik do obsługi żądań

    location / {
        # try_files sprawdza po kolei:
        # 1) czy istnieje plik dokładnie o ścieżce z URL ($uri)
        # 2) czy istnieje katalog o tej ścieżce ($uri/)
        # 3) jeśli nie istnieje ani plik ani katalog -> przekaż request do /index.php
        # $is_args$args zachowuje query string, np. /login?x=1
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        include fastcgi_params;           # dołącza standardowe parametry FastCGI, takie jak SCRIPT_FILENAME, QUERY_STRING itp.
        fastcgi_pass php:9000;            # przekazuje do kontenera "php" na port 9000 (PHP-FPM zwykle tam nasłuchuje)

        # SCRIPT_FILENAME mówi PHP-FPM jaki konkretny plik na dysku ma uruchomić
        # $document_root = /app (z "root /app/")
        # $fastcgi_script_name = np. /index.php
        # razem daje: /app/index.php
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;  
    }
}